Update Application.java
playframework/playframework pull request #10454
Opened 2020-09-23 15:34 UTC by manishbansal8843

Due to this, `longComputation` method body is not getting displayed while rendering this java file in [documentation ](https://www.playframework.com/documentation/2.8.x/JavaAkka).

2020-09-25 07:51 UTC, mkurz requested changes
Please see comment

2020-09-25 07:51 UTC, mkurz commented on documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/async/Application.java
> +
We don't want the fake `longComputation` to be shown, instead we should hide it completely, by skipping all of its lines:
```suggestion
  // ###skip: 3
```

2020-10-10 10:26 UTC, manishbansal8843 commented
@mkurz Gentle reminder :)

2020-10-26 21:11 UTC, mkurz approved these changes

2020-10-26 21:12 UTC, merged

2020-10-26 21:12 UTC, mkurz commented
@Mergifyio backport master