[2.8.x] Run scripted tests on sbt 1.4.x + refactoring
playframework/playframework pull request #10723
Opened 2021-02-25 20:40 UTC by mkurz

Backport of #10655
Only difference: The 2.8.x branch still runs tests against sbt 0.13.x

Requires #10712 merged to make the build green for this PR.

Also, like mentioned in #10655 I am aware that the cron conditions are not here yet. I will add them after #10712 got merged. Then I will restart Travis for this pull request here so all sbt versions will be tested with the fixes in #10712, also see see https://github.com/playframework/playframework/pull/10655#discussion_r583106363 Afterwards I can remove undesired sbt versions and add the cron config.

2021-03-11 17:15 UTC, mkurz commented
@ignasi35 @octonato This backport ready as well!

Example how a cron build will look like (except without sbt 1.2):
https://travis-ci.com/github/playframework/playframework/builds/219526837
which is the build of this commit:
![image](https://user-images.githubusercontent.com/644927/110826635-92d36e80-8295-11eb-97a9-b0a70fa5115b.png)
(the commit before I added the cron conditions)

2021-03-12 10:37 UTC, ignasi35 requested changes
Let's remove a few jobs from the build. The matrix has too many axis and 0.13 should note taking so much attention. Also tempted to remove 1.4x2.12 since early adopters of sbt are likely to be early adopters of scala.

2021-03-12 10:37 UTC, ignasi35 commented on .travis.yml
> +        use: published-local
I wouldn't even care about 0.13 2.13

2021-03-12 10:37 UTC, ignasi35 commented on .travis.yml
> +      script: scripts/test-scripted $SCRIPTED_SBT_0_13 $TEST_SCALA_2_12 'play-sbt-plugin/*3of3'
I'm about to suggest we move anything 0.13 to CRON jobs and let PR builds run lighter.

And, by all means, test only 0.13 scala 2.12: late laggards.

2021-03-12 10:50 UTC, ignasi35 commented
Do we need any mention of 1.4.x support in docs or migration guide?

2021-03-14 12:27 UTC, mkurz commented
@ignasi35 Done, please see the commits I pushed.

> Do we need any mention of 1.4.x support in docs or migration guide?

Not really, there is no action a user needs to take. Just upgrade to Play 2.8.8 and everything works. We can mention that Play now fully supports sbt 1.4 on the [GitHub release page](https://github.com/playframework/playframework/releases) however.

2021-03-15 13:59 UTC, ignasi35 approved these changes

2021-03-15 14:01 UTC, merged