Adds release drafter
playframework/playframework pull request #10730
Opened 2021-03-01 13:30 UTC by ignasi35

2021-03-02 20:34 UTC, octonato approved these changes
LGTM

2021-03-02 21:25 UTC, ihostage requested changes

2021-03-02 21:25 UTC, ihostage commented on .github/release-drafter.yml
> +change-template: '- $TITLE [#$NUMBER](https://github.com/playframework/play-grpc/issues/$NUMBER) by [@$AUTHOR](https://github.com/$AUTHOR)'
```suggestion
change-template: '- $TITLE [#$NUMBER](https://github.com/playframework/playframework/issues/$NUMBER) by [@$AUTHOR](https://github.com/$AUTHOR)'
```

2021-03-02 21:25 UTC, ihostage commented on .github/workflows/release-drafter.yml
> +      - uses: raboof/release-drafter@v5
@ignasi35 On `akka-grpc` uses another 🤔 
https://github.com/akka/akka-grpc/blob/master/.github/workflows/release-drafter.yml#L14
```
- uses: release-drafter/release-drafter@v5
```

2021-03-02 21:25 UTC, ihostage commented on release-drafter.yml
> +# Config for https://github.com/toolmantim/release-drafter
This file not used and can be removed if I right understand

2021-03-04 16:34 UTC, ignasi35 commented on release-drafter.yml
> +# Config for https://github.com/toolmantim/release-drafter
This file is used but it's not referenced anywhere because it's the default location (see docs https://github.com/release-drafter/release-drafter#configuration )

2021-03-04 16:35 UTC, ignasi35 commented on .github/workflows/release-drafter.yml
> +      - uses: raboof/release-drafter@v5
```suggestion
      - uses: release-drafter/release-drafter@v5
```

2021-03-04 17:21 UTC, ignasi35 commented on release-drafter.yml
> +# Config for https://github.com/toolmantim/release-drafter
🤦🏼‍♂️ this file is in `ROOT/`. This is wrongly McWrong wrong.

2021-03-04 17:25 UTC, ihostage approved these changes

2021-03-08 10:45 UTC, octonato approved these changes

2021-03-08 10:46 UTC, merged