Binders for OptionalInt, OptionalLong, OptionalDouble
playframework/playframework pull request #10825
Opened 2021-04-13 11:34 UTC by PromanSEW

# Pull Request Checklist

* [X] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [X] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [X] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [X] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [X] Have you added copyright headers to new files?
* [ ] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #10816

## Purpose

Add binders for Java `OptionalInt`, `OptionalLong`, `OptionalDouble`

## References

#10816

2021-04-14 20:07 UTC, mkurz requested changes
Thanks for the pull request.
Please see my comments above :point_up: you need to add the `javascriptUnbind` methods for each binder.

Plus two more things :point_down: 

First you also need to add `JavascriptLiteral`s for each OptionalXXX type. Like we have for `Optional` here:
https://github.com/playframework/playframework/blob/9852822da1b7e6b50607967d0409e760a2d9be6f/core/play/src/main/scala/play/api/mvc/Binders.scala#L258-L262

E.g. for `OptionalInt` you have to add:

```scala
  /**
   * Convert a Java OptionalInt to Javascript literal (use "null" for an empty OptionalInt)
   */
  implicit def literalJavaOptionalInt: JavascriptLiteral[OptionalInt] =
    (value: OptionalInt) => value.asScala.map(_.toString).getOrElse("null")
````

Same for `OptionalLong` and `OptionalDouble` please.

Second, please add tests, I think that should be here: https://github.com/playframework/playframework/tree/master/dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation
E.g. look in the `conf/routes` file, [there](https://github.com/playframework/playframework/blob/9852822da1b7e6b50607967d0409e760a2d9be6f/dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/conf/routes#L27) is a route for an `Optional` param, which points to [this action method](https://github.com/playframework/playframework/blob/9852822da1b7e6b50607967d0409e760a2d9be6f/dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/app/controllers/Application.scala#L62-L64).
Finally a test is defined [here](https://github.com/playframework/playframework/blob/9852822da1b7e6b50607967d0409e760a2d9be6f/dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/RouterSpec.scala#L237-L250).
Please do similar tests for `OptionalInt`, `OptionalDouble` and `OptionalLong`.
Also it would be good to add a test with default values, [see here](https://github.com/playframework/playframework/blob/9852822da1b7e6b50607967d0409e760a2d9be6f/dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/conf/routes#L49).

Bonus: You could also add tests for the Javascript reverse routes (to test the literals you add, etc.) here: https://github.com/playframework/playframework/blob/28f19894deae8712682352acf53d99eb4a24da46/dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/assets/JavaScriptRouterSpec.js Just re-use the routes you will add for the tests above.
(Also, for this to work I think you need to the reverse routes here: https://github.com/playframework/playframework/blob/9852822da1b7e6b50607967d0409e760a2d9be6f/dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/app/utils/JavaScriptRouterGenerator.scala#L15-L24)


Thanks!

2021-04-15 03:12 UTC, PromanSEW commented
Unfortunately, I could not run tests locally because of error:
```
D:\Documents\GitHub\playframework\dev-mode\routes-compiler\src\main\scala\play\routes\compiler\RoutesGenerator.scala:222:11
not found: value static
          static.twirl
```

2021-04-15 03:15 UTC, PromanSEW commented on dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/assets/JavaScriptRouterSpec.js
> +    });
I'm not sure about this test, is it right?

2021-04-15 08:21 UTC, PromanSEW commented
I don't know what test is failing. Travis does not write that

2021-04-15 08:25 UTC, mkurz commented on dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/conf/routes
> +GET         /take-joptdouble        controllers.Application.takeOptionaDouble(x: java.util.OptionalDouble)
You have the same typo in all these three lines: `takeOptionaInt` -> `takeOptionalInt` (you miss the letter l in Optiona**l**)

2021-04-15 08:27 UTC, mkurz commented on dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/conf/routes
> +GET         /take-joptdouble        controllers.Application.takeOptionaDouble(x: java.util.OptionalDouble)
> Travis does not write that

See https://travis-ci.com/github/playframework/playframework/jobs/498658780#L1863-L1865
```scala
[info] [error] /tmp/sbt_e18051c6/routes-compiler-routes-compilation/target/scala-2.12/routes/main/router/Routes.scala:488:19: value takeOptionaInt is not a member of controllers.Application
[info] [error]     Application_1.takeOptionaInt(fakeValue[java.util.OptionalInt]),
[info] [error]       
```

2021-04-15 10:20 UTC, PromanSEW commented
Why?
```
[info] [info] The JavaScript router
[info] [info]   + should generate a url
[info] [info]   + should provide the GET method
[info] [info]   + should provide the POST method
[info] [info]   + should add parameters to the path
[info] [info]   + should add parameters to the query string
[info] [info]   ! should add default parameters to the query string
[info] [error] TypeError: jsRoutes.controllers.Application.takeOptionalIntWithDefault is not a function
```

2021-04-15 11:50 UTC, PromanSEW commented on dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/assets/JavaScriptRouterSpec.js
> +    });
```
[info] [info] The JavaScript router
[info] [info]   + should generate a url
[info] [info]   + should provide the GET method
[info] [info]   + should provide the POST method
[info] [info]   + should add parameters to the path
[info] [info]   + should add parameters to the query string
[info] [info]   ! should add default parameters to the query string
[info] [error] AssertionError [ERR_ASSERTION]: '/take-joptint-d?x=123' == '/take-joptint-d'
```

2021-04-15 12:12 UTC, PromanSEW commented on dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/assets/JavaScriptRouterSpec.js
> +    });
I think it must be like:
```javascript
    it("should generate a url for default parameters", function() {
        var data = jsRoutes.controllers.Application.takeOptionalIntWithDefault();
        assert.equal("/take-joptint-d", data.url);
    });
```

2021-04-15 13:13 UTC, PromanSEW commented on core/play/src/main/scala/play/api/mvc/Binders.scala
> +      )
It can be also `bindableInt` instead of `implicitly[QueryStringBindable[Int]]`

2021-04-15 13:32 UTC, mkurz commented on dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/assets/JavaScriptRouterSpec.js
> +    });
> I think it should be like:

Yeah, I think your comment is right. However, what do you think of changing the description of the tests a bit and add three more, like:

```javascript
    it("should generate a url for an OptionalInt parameter (which has a default)", function() {
        var data = jsRoutes.controllers.Application.takeOptionalIntWithDefault();
        assert.equal("/take-joptint-d", data.url);
    });

    it("should generate a url for an OptionalInt parameter (which has a default) when default param value is passed", function() {
        var data = jsRoutes.controllers.Application.takeOptionalIntWithDefault(123);
        assert.equal("/take-joptint-d", data.url);
    });

    it("should add an OptionalInt parameter (which has a default) to the query string", function() {
        var data = jsRoutes.controllers.Application.takeOptionalIntWithDefault(987);
        assert.equal("/take-joptint-d?x=987", data.url);
    });

    it("should generate a url for an OptionalInt parameter", function() {
        var data = jsRoutes.controllers.Application.takeOptionalInt();
        assert.equal("/take-joptint", data.url);
    });

    it("should add an OptionalInt parameter to the query string", function() {
        var data = jsRoutes.controllers.Application.takeOptionalInt(123);
        assert.equal("/take-joptint?x=123", data.url);
    });
```

2021-04-15 13:34 UTC, mkurz commented on core/play/src/main/scala/play/api/mvc/Binders.scala
> +      )
Yes, there are different options. Let's keep it how it is :+1:

2021-04-15 13:37 UTC, mkurz commented on dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/RouterSpec.scala
> +  )
@PromanSEW Please also add similar tests with calling `testQueryParamBindingWithDefault`, like this here: https://github.com/playframework/playframework/blob/2.8.8/dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/RouterSpec.scala#L502-L515
Thanks!

2021-04-15 14:50 UTC, mkurz commented on dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/RouterSpec.scala
> +    "take-joptint-d",
Please remove `-d` from `take-joptint-d`, it will be added automatically:
https://github.com/playframework/playframework/blob/f4a3cbc4aef395189ea3b0094316d04559ff4098/dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/RouterSpec.scala#L103

2021-04-15 14:56 UTC, mkurz approved these changes

2021-04-15 17:00 UTC, PromanSEW commented
What's wrong now? -_-
```
[info] [info] bind java.util.OptionalInt parameter with default value from the query string
[info] [info]   + successfully
[info] [error]   x when there is a parameter but without value (=empty string)
[info] [error]    'emptyOptionalInt' != '123' (RouterSpec.scala:565)
[info] [error]   x when there is a parameter but without value (=empty string) and without equals sign
[info] [error]    'emptyOptionalInt' != '123' (RouterSpec.scala:565)
[info] [error]   x when there is no parameter at all
[info] [error]    'emptyOptionalInt' != '123' (RouterSpec.scala:569)
[info] [info] bind java.util.OptionalLong parameter with default value from the query string
[info] [info]   + successfully
[info] [error]   x when there is a parameter but without value (=empty string)
[info] [error]    'emptyOptionalLong' != '123' (RouterSpec.scala:579)
[info] [error]   x when there is a parameter but without value (=empty string) and without equals sign
[info] [error]    'emptyOptionalLong' != '123' (RouterSpec.scala:579)
[info] [error]   x when there is no parameter at all
[info] [error]    'emptyOptionalLong' != '123' (RouterSpec.scala:583)
[info] [info] bind java.util.OptionalDouble parameter with default value from the query string
[info] [info]   + successfully
[info] [error]   x when there is a parameter but without value (=empty string)
[info] [error]    'emptyOptionalDouble' != '1.23' (RouterSpec.scala:593)
[info] [error]   x when there is a parameter but without value (=empty string) and without equals sign
[info] [error]    'emptyOptionalDouble' != '1.23' (RouterSpec.scala:593)
[info] [error]   x when there is no parameter at all
[info] [error]    'emptyOptionalDouble' != '1.23' (RouterSpec.scala:597)
```

2021-04-16 07:39 UTC, mkurz commented on dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/assets/JavaScriptRouterSpec.js
> +        assert.equal("/take-joptint-d?x=123", data.url);
I am not 100% sure if this is supposed to be correct. AFAIK, when the default is passed, it should not add the param, but maybe I am wrong. I will have a look later to day..

2021-04-16 09:42 UTC, PromanSEW commented on dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/assets/JavaScriptRouterSpec.js
> +        assert.equal("/take-joptint-d?x=123", data.url);
If the value is specified explicitly, there is no need to compare with the default IMHO

2021-04-20 07:23 UTC, PromanSEW commented
@mkurz any updates?

2021-04-20 07:58 UTC, mkurz commented on dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/assets/JavaScriptRouterSpec.js
> +        assert.equal("/take-joptint-d?x=123", data.url);
OK, I checked: I was a bit confused.
Actually the Java reverse routes actually are intellegent enough to check if the param is the default, and if so, it will _not_ be added to the query string:
```java
// Java reverse route:
routes.controllers.Application.takeOptionalIntWithDefault(123);
```
will result in `/take-joptint-d` in Java.
However the _Javascript_ reverse route don't care if the param is the default and always adds the param, like in this test here.
So everything OK :+1:

2021-04-20 08:00 UTC, mkurz commented
@Mergifyio backport 2.8.x

2021-04-20 08:00 UTC, merged