Add support for trait/interface-based dependency injection frameworks
playframework/playframework pull request #10968
Opened 2021-08-29 18:51 UTC by christian-schlichtherle

While the Play Framework has been supporting compile time dependency injection (DI) frameworks for a while now, its design has always been biased towards JSR 330 based DI, i.e. injection into constructors, methods or even fields. However, that's not the only way to do DI: Recent development has seen a rise in functional composition for the purpose of DI (think Kleisli etc). But there's another, even simpler, yet more versatile method of DI: Let the compiler automatically implement abstract methods to return the dependencies of the components. This approach has many advantages, but discussing them here is beyond the scope of a PR. If you're interested, please check out my own little invention, [Bali DI](https://bali-di.namespace.global).

Finally, this PR adds support for trait/interface dependency injection frameworks in a backwards compatible way. As you can see, the changes are rather small and they perfectly match the `*Components`-like naming pattern which is already present in the framework.

I hope you will see my point and support this PR. If more work needs to be done, please let me know. For example, the suggested name for the new trait/interface `BuiltinComponentsWithContext` could be renamed to `ContextBasedBuiltinComponents` in order to match the other `*Components` interfaces, which is a reminiscent of the Cake pattern.

2021-08-30 03:30 UTC, gmethvin requested changes
This seems like a reasonable change since traits/interfaces are more flexible than classes. This also might be a nicer syntax for creating standalone Play applications—e.g. in tests—since this:

```scala
val components = new BuiltInComponentsWithContext with HttpFiltersComponents {
  override val context: Context = Context.create(Environment.simple())
  override def router: Router = Router.from {
    case GET(p"/hello/$to") => Action { Ok(s"Hello $to") }
  }
}
```

arguably looks cleaner than:

```scala
val context = Context.create(Environment.simple())
val components = new BuiltInComponentsFromContext(context) with HttpFiltersComponents {
  override def router: Router = Router.from {
    case GET(p"/hello/$to") => Action { Ok(s"Hello $to") }
  }
}
```

I don't think it's appropriate to mention Bali DI specifically in the scaladoc/javadoc. Mentioning a library in our documentation suggests that Play specifically supports the library in some way.

Also, it would be nice to have some tests that use the new code.

2021-08-30 03:30 UTC, gmethvin commented on core/play/src/main/scala/play/api/ApplicationLoader.scala
> +  val context: ApplicationLoader.Context
I think this should be a `def`. Generally implementations should only need to create a single instance, but I can imagine situations where someone would want it to be a `lazy val`, or simply a `def` that returns some instance passed in from outside.

2021-08-30 03:30 UTC, gmethvin commented on core/play-integration-test/src/it/java/play/BuiltInComponentsFromContextTest.java
> +    public Environment environment() {
What is this needed for?

2021-08-30 06:04 UTC, christian-schlichtherle commented on core/play-integration-test/src/it/java/play/BuiltInComponentsFromContextTest.java
> +    public Environment environment() {
The compiler mandates this because `environment()` is now present in two subclasses.

2021-08-30 06:05 UTC, christian-schlichtherle commented
> This seems like a reasonable change since traits/interfaces are more flexible than classes. This also might be a nicer syntax for creating standalone Play applications—e.g. in tests—since this:
> 
> ```scala
> val components = new BuiltInComponentsWithContext with HttpFiltersComponents {
>   override val context: Context = Context.create(Environment.simple())
>   override def router: Router = Router.from {
>     case GET(p"/hello/$to") => Action { Ok(s"Hello $to") }
>   }
> }
> ```
> 
> arguably looks cleaner than:
> 
> ```scala
> val context = Context.create(Environment.simple())
> val components = new BuiltInComponentsFromContext(context) with HttpFiltersComponents {
>   override def router: Router = Router.from {
>     case GET(p"/hello/$to") => Action { Ok(s"Hello $to") }
>   }
> }
> ```
> 
> I don't think it's appropriate to mention Bali DI specifically in the scaladoc/javadoc. Mentioning a library in our documentation suggests that Play specifically supports the library in some way.
> 
> Also, it would be nice to have some tests that use the new code.

I'll change the documentation.

2021-08-30 06:08 UTC, christian-schlichtherle commented on core/play/src/main/scala/play/api/ApplicationLoader.scala
> +  val context: ApplicationLoader.Context
An abstract `val` can always be implemented with a `lazy val` and in fact, that's exactly what Bali DI would do for you automatically if this is present.

The added flexibility of a `def` doesn't make much sense and cannot be exploited when using the `BuiltinComponentsFromContext` class anyway, so I decided to go with a `val`.

2021-08-30 06:10 UTC, christian-schlichtherle commented on core/play/src/main/scala/play/api/ApplicationLoader.scala
> + * This variant is best suited for use with any JSR 330 based dependency injection framework,
I'll remove the reference to JSR 330, Guice and Bali DI. Apparently it raises more questions.

2021-08-30 06:48 UTC, christian-schlichtherle commented
I have updated this PR according to our conversation. I have also ensured parity between the Java and Scala implementation. The super trait/class is now named `ContextBasedBuiltinComponents` to match the naming pattern of all your other `*Components` types.

2021-08-30 06:53 UTC, christian-schlichtherle commented
As for the tests, after this refactoring, the `BuiltinComponentsFromContext` class is just a shim on top of `ContextBasedBuiltinComponents`. So any existing test for the primer automatically covers the latter. That's why I don't think any new tests are required.

2021-08-30 17:46 UTC, smarter commented on core/play/src/main/scala/play/api/ApplicationLoader.scala
> +  val context: ApplicationLoader.Context
> An abstract val can always be implemented with a lazy val 

This is no longer true in Scala 3 for soundness reasons (lazy vals unlike vals cannot appear in path-dependent types without additional checks)

2021-08-30 19:02 UTC, gmethvin commented on core/play/src/main/scala/play/api/ApplicationLoader.scala
> +  val context: ApplicationLoader.Context
Either way, we typically we express a dependency in traits as a `def`, even if there should only be one instance, so I think it makes sense to use a `def`.

2021-08-30 19:16 UTC, gmethvin commented on core/play/src/main/scala/play/api/ApplicationLoader.scala
> + * It is best suited for use with any dependency injection frameworks which favor constructor injection to supply
I think it just confuses things more to say this. Most JSR-330 frameworks favor constructor injection but they declare bindings dynamically via reflection, so for those you'd want to use Play's built-in runtime dependency injection support rather than this.

The abstract class and the trait are both meant to be used by mixing in traits declared as dependencies. They're essentially two slightly different flavors of the same thing.

I'd just remove the statements about being best suited for a particular type of framework.

2021-08-30 19:16 UTC, gmethvin commented on core/play/src/main/java/play/ContextBasedBuiltInComponents.java
> +public abstract class ContextBasedBuiltInComponents implements BuiltInComponents {
Why is this an abstract class rather than a trait?

2021-08-30 19:16 UTC, gmethvin commented on core/play-integration-test/src/it/java/play/BuiltInComponentsFromContextTest.java
> +    public Environment environment() {
Where else does the method show up? This is something the user would have to do, so it's not ideal from an API design standpoint. If we need to keep it we probably should add something to the migration guide.

2021-08-30 20:43 UTC, christian-schlichtherle commented on core/play-integration-test/src/it/java/play/BuiltInComponentsFromContextTest.java
> +    public Environment environment() {
Sorry, I meant superclasses of course. It implements `RedirectHttpsComponents`.

2021-08-30 20:46 UTC, christian-schlichtherle commented on core/play/src/main/scala/play/api/ApplicationLoader.scala
> +  val context: ApplicationLoader.Context
Changed.

2021-08-30 20:49 UTC, christian-schlichtherle commented on core/play/src/main/java/play/ContextBasedBuiltInComponents.java
> +public abstract class ContextBasedBuiltInComponents implements BuiltInComponents {
Because of all the poor man's lazy vals in it. Otherwise, you wouldn't have parity between the Java and the Scala API. Also, without all the poor man's lazy vals it would still be required for the user to implement it and that would make the whole change useless.

2021-08-30 20:53 UTC, christian-schlichtherle commented on core/play/src/main/scala/play/api/ApplicationLoader.scala
> + * It is best suited for use with any dependency injection frameworks which favor constructor injection to supply
Changed.

2021-08-30 23:41 UTC, gmethvin commented on core/play-integration-test/src/it/java/play/BuiltInComponentsFromContextTest.java
> +    public Environment environment() {
This should compile fine without this override because `environment` is already implemented by `BuiltInComponentsFromContext`.

2021-08-30 23:42 UTC, gmethvin reviewed
you'll also need to format the code before this gets merged

2021-08-30 23:50 UTC, christian-schlichtherle commented on core/play-integration-test/src/it/java/play/BuiltInComponentsFromContextTest.java
> +    public Environment environment() {
But it doesn't because it's only a `default` method in the `ContextBasedBuiltinComponents` interface.

2021-08-31 00:13 UTC, christian-schlichtherle commented
> you'll also need to format the code before this gets merged

Changed.

2021-08-31 09:22 UTC, christian-schlichtherle commented
Changed again according to instructions in error message from Travis CI.

2021-08-31 20:19 UTC, gmethvin commented on core/play-integration-test/src/it/java/play/BuiltInComponentsFromContextTest.java
> +    public Environment environment() {
Are you sure it's needed? I checked out your PR branch and it still seems to compile.

If it is needed now, then it's a breaking change we'd have to consider. At the very least you'd need to explain in the migration guide what needs to be done.

2021-08-31 20:21 UTC, gmethvin commented on core/play-integration-test/src/it/java/play/BuiltInComponentsFromContextTest.java
> +    public Environment environment() {
It's actually a regular method definition in `ContextBasedBuiltinComponents`, not a default method.

2021-09-01 05:48 UTC, christian-schlichtherle commented on core/play-integration-test/src/it/java/play/BuiltInComponentsFromContextTest.java
> +    public Environment environment() {
Yes, after many changes now it is. I’ll change it.

2021-09-01 07:13 UTC, christian-schlichtherle commented on core/play-integration-test/src/it/java/play/BuiltInComponentsFromContextTest.java
> +    public Environment environment() {
Changed

2021-09-01 14:24 UTC, christian-schlichtherle commented
@gmethvin, I'm done. Please review again.

2021-09-01 21:30 UTC, gmethvin approved these changes
lgtm

2021-09-02 20:51 UTC, merged