Documented the change from ValidationError to JsonValidationError in Migration-2.6
playframework/playframework pull request #11075
Opened 2021-12-28 08:59 UTC by GKuldeepak-Knoldus

# Pull Request Checklist

* [ ] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [ ] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [ ] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ ] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [ ] Have you added copyright headers to new files?
* [ ] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

## Fixes

Fixes #8190

2021-12-29 23:23 UTC, mkurz requested changes

2021-12-29 23:23 UTC, mkurz commented on documentation/manual/releases/release26/migration26/Migration26.md
> +Also, there is small change in play-json API, `data.validation.ValidationError` has been upgraded to `libs.json.JsonValidationError`. For example, if you have code like:
Is there reason you omitted `play.api.` from the package name?
I think it would be better if we write out the full package names:
`play.api.data.validation.ValidationError` and `play.api.libs.json.JsonValidationError`

Also I think `...has been changed to...` sounds better than `...has been upgraded to...`.

2021-12-30 05:15 UTC, GKuldeepak-Knoldus commented on documentation/manual/releases/release26/migration26/Migration26.md
> +Also, there is small change in play-json API, `data.validation.ValidationError` has been upgraded to `libs.json.JsonValidationError`. For example, if you have code like:
I have done the changes. Please review now.

2021-12-30 10:02 UTC, mkurz approved these changes
Thanks!

2021-12-30 10:02 UTC, merged