Changed to accept a test address to bind
playframework/playframework pull request #11179
Opened 2022-03-10 09:42 UTC by morellik

# Pull Request Checklist

* [ x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [ x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x ] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x ] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [ x] Have you added copyright headers to new files?
* [x ] Have you checked that both Scala and Java APIs are updated?
* [x ] Have you updated the documentation for both Scala and Java sections?
* [x ] Have you added tests for any changed functionality?

## Fixes

Fixes #10927

## Purpose

Allow changing address to bind to

2022-03-10 09:42 UTC, lightbend-cla-validator commented
At least one commit author (morelli@cerm.unifi.it) is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

2022-03-10 11:27 UTC, mkurz requested changes
Thanks! Please see the other comment I made.

Also if you look at the status of the pull request you see that Travis is not happy. If you look into it, you will see that some files are not correctly formatted:
```
[warn] /home/travis/build/playframework/playframework/testkit/play-test/src/main/scala/play/api/test/Helpers.scala isn't formatted properly!
[warn] /home/travis/build/playframework/playframework/testkit/play-test/src/main/scala/play/api/test/TestServer.scala isn't formatted properly!
[warn] /home/travis/build/playframework/playframework/testkit/play-test/src/main/scala/play/api/test/TestServerFactory.scala isn't formatted properly!
```
(See https://app.travis-ci.com/github/playframework/playframework/jobs/562788374#L317)

You can format them by running `scalafmt` in sbt.

After that, please push your changes again. Thanks!

2022-03-10 11:27 UTC, mkurz commented on dev-mode/run-support/src/test/scala/play/runsupport/FilterArgsSpec.scala
> +      properties: Seq[(String, String)] = Seq,
Please undo this change, thanks!

2022-03-10 13:09 UTC, morellik commented
Done

2022-03-10 13:37 UTC, BillyAutrey commented on testkit/play-test/src/main/scala/play/api/test/Helpers.scala
> +  lazy val testServerAddress: String = sys.props.get("testserver.address").orElse(sys.env.get("PLAY_TEST_SERVER_HTTP_ADDRESS")).getOrElse("0.0.0.0")
If you allow the reference.conf to optionally parse for this environment variable, you don't need the middle part here.

2022-03-10 14:37 UTC, morellik commented on dev-mode/run-support/src/test/scala/play/runsupport/FilterArgsSpec.scala
> +      properties: Seq[(String, String)] = Seq,
I followed the suggestions of mkurz posted here https://github.com/playframework/playframework/issues/10927

2022-03-10 14:38 UTC, morellik commented on testkit/play-test/src/main/scala/play/api/test/Helpers.scala
> +  lazy val testServerAddress: String = sys.props.get("testserver.address").orElse(sys.env.get("PLAY_TEST_SERVER_HTTP_ADDRESS")).getOrElse("0.0.0.0")
I followed the suggestions of mkurz posted here https://github.com/playframework/playframework/issues/10927

2022-05-04 15:18 UTC, PromanSEW commented
Should be targeted to `main` branch instead
Also I don't understand why GitHub did not add link issue to "Successfully merging this pull request may close these issues" block...

2023-05-31 22:29 UTC, mkurz commented
@morellik thank you very much, however I merged #11509 instead which also contained tests and docs updates.

2023-05-31 22:29 UTC, closed without merging