[2.9.x] Change method names for PathBindable and QueryStringBindable
playframework/playframework pull request #11244
Opened 2022-04-17 06:00 UTC by takapi327

# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [ ] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [ ] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes [#11198](https://github.com/playframework/playframework/issues/11198)

## Purpose
Both PathBindable and QueryStringBindable are traits, but currently the two cannot be inherited simultaneously.

Since there is no restriction on inheriting from PathBindable and QueryStringBindable at the same time, both of them can be inherited at the same time.

## Background Context
Currently, when you make an object PathBindable it's impossible to also make it QueryStringBindable at the same time.

If you create an object that inherits from both PathBindable and QueryStringBindable, the bind, unbind, javascriptUnbind and transform methods will conflict.

Therefore, even if these four methods are deprecated and redefined with different names, conflicts will still occur.

This is because it is difficult to deal with deprecations and all method names must be changed and released in the 2.9.x major version.

## Note
- I am new to creating pull requests for this project. Please let me know if there is anything I am doing wrong or omitting to address.
- I couldn't find a branch for 2.9.x, so I'm merging it into main. Please change to the appropriate branch.
- I made an addendum to the documentation for scala migration, but could not find the documentation for java migration. I would like to know what documentation I should modify if I change the java code.

2022-04-17 06:00 UTC, lightbend-cla-validator commented
Hi @takapi327,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

2022-04-19 12:08 UTC, mkurz requested changes
Thank you very much!

Please see my comments, also we need to update the documentation:
* https://www.playframework.com/documentation/2.8.x/ScalaRequestBinders
* https://www.playframework.com/documentation/2.8.x/RequestBinders

The source of that pages are here:
* https://github.com/playframework/playframework/blob/main/documentation/manual/working/javaGuide/advanced/routing/RequestBinders.md
* https://github.com/playframework/playframework/blob/main/documentation/manual/working/scalaGuide/advanced/routing/ScalaRequestBinders.md

Also IMHO we should rename `RequestBinders.md` to `JavaRequestBinders.md` to be more consistent with the rest of the docs.

Thanks again!

2022-04-19 15:12 UTC, takapi327 commented on documentation/manual/releases/release29/migration29/Migration29.md
> +| **Deprecated method**                                      | **New method**
Thank you!
I'll fix it

2022-04-19 15:13 UTC, takapi327 commented on documentation/manual/releases/release29/migration29/Migration29.md
> +Methods renamed in trait [`play.api.mvc.QueryStringBindable`](api/scala/play/api/mvc/QueryStringBindable.html)
Thank you! Understood. I will add the same.

2022-04-20 06:28 UTC, takapi327 commented
@mkurz Thank you very much!
We have corrected the information you reviewed.

2022-04-24 20:26 UTC, mkurz commented
Triggering CI by closing/re-opening...

2022-05-11 07:28 UTC, takapi327 commented
@mkurz Sorry for the delay.
Fixed a problem with an error in the `sbt +mimaReportBinaryIssues` command.
Please check to see if there are any problems with the corrected content.

2022-05-11 14:15 UTC, mkurz commented
@takapi327 There are still problems, please see here: https://github.com/playframework/playframework/runs/6385057076?check_suite_focus=true

2022-05-11 16:06 UTC, takapi327 commented on project/BuildSettings.scala
> +      // Remove deprecated methods from PathBindable and QueryStringBindable for Java
I have described all the patterns, although redundant, because doing so in * would exclude all future additions.

Would it be better to use * and rewrite it when I add new methods, etc.?

2022-05-15 06:04 UTC, takapi327 commented on project/BuildSettings.scala
> +      // Remove deprecated methods from PathBindable and QueryStringBindable for Java
@mkurz Sorry.
Formatting problems have also been resolved.

2022-05-28 23:21 UTC, gmethvin commented
I know I'm late to this discussion, but is this worth the breaking change? I would argue it's not.

2022-05-28 23:32 UTC, gmethvin requested changes
I can see the argument for doing this in the Java API, because the bound class itself needs to implement `PathBindable` or `QueryStringBindable`, but there's no real benefit to doing this for the Scala API, because `PathBindable` and `QueryStringBindable` are type classes, and are provided as independent implicit values. The `PathBindable` and `QueryStringBindable` do distinct things so I don't see much value in having them implemented by the same object in Scala.

2023-05-05 11:54 UTC, mkurz commented
Renaming the method alone doesn't really help, since that doesn't magically make path + query string binding work at the same time.
I am closing this PR for now since I don't think this is the way to go. We can always revisit it later if needed.
See https://github.com/playframework/playframework/issues/11198#issuecomment-1536145208 for explanations.

2023-05-05 11:54 UTC, closed without merging