To refactor `BodyPartParser` of `Multipart` in order to avoid StackOverflowError easily
playframework/playframework pull request #11360
Opened 2022-07-12 06:31 UTC by yousuketto

# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [ ] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #10590 

## Purpose
Refactoring to avoid StackOverflowError easily when parsing multipart/form-data on `BodyPartParser` of `Multipart`

## Background Context
The current code uses recursive call so StackOverflowError is occurred. We need to estimate `maxMemoryBuffer` size in order to avoid the error.
https://github.com/playframework/playframework/issues/10590

I guess refactoring the code to use @tailrec or loop would avoid the error without estimating the size of `maxMemoryBuffer`.

## References
https://github.com/playframework/playframework/discussions/11347

2022-07-12 07:01 UTC, mkurz requested changes
Tests fail because formatting isn't correct, please run `scalafmt` and push again, thanks!

2022-07-12 07:28 UTC, yousuketto commented
Thanks for notification. I executed scalafmt and pushed again.

2022-07-13 21:16 UTC, yousuketto commented
I checked 3 checkboxes and I write why I checked.
Especially, I have no idea to test this pull request with a unit test so please tell me them if anyone have.

2022-10-13 17:37 UTC, mkurz approved these changes
Thanks!
I was able to reproduce this with https://github.com/mkurz/playframework-reproducers/tree/main/playframework-10590
I did carefully review your changes and they LGTM.
We have quite extensive tests in https://github.com/playframework/playframework/blob/main/core/play-integration-test/src/it/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala already as far as I can remember since I worked on a related issue in #10236 so we are good to merge here.

We might be able to add a scripted tests however later that shows it doesn't get killed when receiving a form with many fields.

2022-10-13 17:37 UTC, merged

2022-10-13 17:38 UTC, mkurz commented
@Mergifyio backport main