Add resource scheme for #11253
playframework/playframework pull request #11371
Opened 2022-07-31 16:01 UTC by kijuky

# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things

## Fixes

This pull request only supports the `resource` protocol. I will not add support for other graalvm features.

## Purpose

graalvm requires resources to be accessed with a protocol called `resource`. So Play needs to handle the `resource` protocol properly.

## Background Context

- The implementation has been copied over from the existing `bundleresource` protocol as it is functionally equivalent.
- Accessing the directory results in an invalid file download. This is because the `resource` protocol cannot tell if the file is a directory.

## References

Discussion for #11253

2022-07-31 16:01 UTC, lightbend-cla-validator commented
At least one commit author (kizuki-yasue@m3.com) is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

2022-08-07 09:06 UTC, kijuky commented
Please help me. 😢 

Test case "play-sbt-plugin/shutdown-downing" is failing. However, I was unable to reproduce the failure when running at local or [at CI on a forked repository](https://github.com/kijuky/playframework/pull/1). Where is the cause...?

2022-08-08 07:53 UTC, mkurz commented
@kijuky The `shutdown-downing` scripted test is flaky, it's not your fault 😉 I restarted it

2022-08-11 14:45 UTC, kijuky commented
@mkurz 
Thank you very much! It helped me a lot.

2022-08-11 15:03 UTC, kijuky commented
In the current implementation, accessing the directory results in invalid file download behavior. To avoid this, we need to add an Environment argument to the Assets constructor for directory detection.
https://github.com/playframework/playframework/compare/main...kijuky:add-resource-scheme:feature/add-resource-scheme-2

Would it be better to include the diff in this pull request?

2022-09-03 11:15 UTC, gmethvin commented on core/play/src/main/scala/play/api/controllers/Assets.scala
> +      case "resource"                  => getLastModified[URLConnection](c => c.getLastModified)
would be cleaner to do `case "bundle" | "resource" | "bundleresource" => ...`

2022-09-03 11:18 UTC, gmethvin commented
@kijuky did you want to add the other changes in this PR? They're related so I think it's fine. But if you prefer you can open a different PR.

2022-09-06 09:55 UTC, mkurz commented
@kijuky Are you able to continue to work on this pull request? Like Greg said, just add the other changes as well, it's fine. Thanks!

2022-09-08 17:19 UTC, kijuky commented
@gmethvin @mkurz Sorry for being late.

> did you want to add the other changes in this PR? They're related so I think it's fine. But if you prefer you can open a different PR.

Thank you for your advice. Added a commit that fixed the directory issue. This required including the `Environment` in the `Assets` class. So more fixes were needed.

2022-09-08 20:08 UTC, gmethvin commented on core/play/src/main/scala/play/utils/Resources.scala
> +      case (bundle, "bundle") =>
For all of these other cases I think we can just call `isDirectory(urlConnection.getURL)`. That'd make the code a bit easier to understand.

2022-10-12 12:39 UTC, mkurz commented
@kijuky Can you have a look at @gmethvin comments?

2022-10-12 14:07 UTC, kijuky reviewed
Very sorry... I didn't run "review changes".

2022-11-07 10:44 UTC, gmethvin commented on core/play/src/main/scala/play/utils/Resources.scala
> +    case "resource"                  => isGraalVMResourceDirectory(classLoader, url)
Thanks for the explanation; it makes more sense now that you've changed the names in the code and added a comment to clarify.

2022-11-07 10:44 UTC, gmethvin approved these changes

2023-04-13 09:48 UTC, mkurz commented on core/play/src/main/scala/play/api/controllers/Assets.scala
> +        if (env != null && Resources.isUrlConnectionADirectory(env.classLoader, connection)) {
For backwards compatibility, shouldn't we keep calling `Resources.isUrlConnectionADirectory` even when env is null?
```suggestion
        if (Resources.isUrlConnectionADirectory(if (env != null) env.classLoader else null, connection)) {
```
Makes sense IMHO.

2023-04-13 09:48 UTC, mkurz requested changes
@kijuky LGTM besides one comment. If we solve that that PR can be merged.

2023-04-13 09:55 UTC, kijuky commented on core/play/src/main/scala/play/api/controllers/Assets.scala
> +        if (env != null && Resources.isUrlConnectionADirectory(env.classLoader, connection)) {
I see. Certainly, even if it already exists, there is a path in the calling hierarchy where classLoader is assumed to be null. I will reflect your suggestions.

2023-04-13 10:05 UTC, mkurz approved these changes
Thanks!

2023-04-13 10:57 UTC, merged