Avoid direct usage of StaticLoggerBinder
playframework/playframework pull request #11419
Opened 2022-09-12 20:43 UTC by jfsoul

# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Partially addresses #11400 by using a method for finding a logger factory that should be compatible with SLF4J 2.0.0. The upgrade itself can be done separately and not backported to `2.8.x`.

## Purpose

Allows consumers to use SLF4J 2.0.0 in their projects without breaking Play 2.8 compatibility.

Makes `LogbackLoggerConfigurator` compatible with SLF4J 2.0.0, which has removed binding via finding a `StaticLoggerBinder` on the classpath, in favour of `ServiceLoader`. In practice, we don't need to implement any `ServiceLoader` logic because SLF4J provides `LoggerFactory.getILoggerFactory` (which is backwards/forwards compatible.)

Updates documentation references to `StaticLoggerBinder` as well.

## Background Context

`getILoggerFactory` has always provided the functionality we require, so it seems like the natural method to use. However it was used originally and changed in https://github.com/playframework/playframework/pull/6025, so perhaps there was a reason for that.

## References

https://github.com/orgs/playframework/discussions/11399

2022-09-12 22:08 UTC, mkurz requested changes
Can you please run `scalafmt` once and push again? Thanks!

2022-09-16 10:36 UTC, merged

2022-09-16 10:36 UTC, mkurz commented
@Mergifyio backport main

2022-09-20 09:47 UTC, mkurz commented
@jfsoul Unfortunately upgrading slf4 to v2 still throws errror, see #11417
Both `play.api.ModeSpecificLoggerSpec` and `play.api.db.evolutions.EvolutionsReaderSpec` are failing:
https://github.com/playframework/playframework/actions/runs/3032587158/jobs/4954378568 each time with 
```
java.lang.ClassCastException: org.slf4j.helpers.NOPLogger cannot be cast to ch.qos.logback.classic.Logger
```
would you have time to take a look to see what's wrong here? Thanks!

2022-09-20 20:43 UTC, jfsoul commented
I think we just need to update logback to 1.3.x or 1.4.x at the same time. Happy to PR that, if you leave it with me for a couple of days.