Add class field dependency injection example doc
playframework/playframework pull request #11836
Opened 2023-05-30 20:40 UTC by dizinfector

## Purpose

Adds one more dependency injection case in documentation

2023-05-31 23:01 UTC, mkurz requested changes
Thanks. So this example bascially shows how to inject into fields. In the docs we recommend constructor injection. Anyway, we can add the example as well, since its meant as hint.

Can you please take a look at my comments? I would prefer using the `javax.inject.*` imports. Thanks!

2023-06-01 20:27 UTC, dizinfector commented on documentation/manual/working/javaGuide/main/dependencyinjection/code/javaguide/di/guice/classfield/Counter.java
> +import javax.inject.ImplementedBy;
Ah, ok, got you wrong :)

2023-06-08 17:16 UTC, dizinfector commented
@mkurz could you please take a look

2023-06-14 08:30 UTC, mkurz approved these changes

2023-06-14 08:30 UTC, merged