Add generated play.http.secret.key at the end of the application.conf file
playframework/playframework pull request #12269
Opened 2023-12-12 17:12 UTC by janani-reddy9

Changed to append the generated play.http.secret.key to the end of file(previously added at the start of the file) so that we do not add the key before comment lines if any.

## Fixes

Fixes #12200

2024-01-23 14:19 UTC, janani-reddy9 commented
Hi @mkurz , Could you check this PR when you have sometime.

2024-01-23 14:21 UTC, mkurz requested changes
If easily possible, I think it would be good to add an empty line before the secret. But only if there is no empty line yet (so we don't end up with 2 empty lines).

2024-01-23 14:21 UTC, mkurz commented on dev-mode/sbt-plugin/src/main/scala/play/sbt/ApplicationSecretGenerator.scala
>          log.warn("Adding application secret to start of file")
```suggestion
        log.warn("Adding application secret to end of file")
```

2024-02-26 21:59 UTC, mkurz commented
@janani-reddy9 Are you still interested in this pull request?

2024-03-12 11:36 UTC, mkurz commented
Pushed a commit to make sure there is an empty line. Tested locally, works (even with empty file).

2024-03-12 11:36 UTC, merged

2024-03-26 21:10 UTC, janani-reddy9 commented
Apologies, @mkurz, got occupied with personal things lately didn't get a chance to look at this.

2024-03-26 21:21 UTC, janani-reddy9 commented on dev-mode/sbt-plugin/src/main/scala/play/sbt/ApplicationSecretGenerator.scala
> +          .filter(!_.isEmpty)
Probably `.filter(nonEmpty)` too would've worked